services:
  esdb-node:
    image: eventstore/eventstore:latest
    container_name: eventstore
    ports:
      - "2113:2113"
    environment:
      - EVENTSTORE_INSECURE=True
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=True
    command: "--insecure --run-projections=All --enable-atom-pub-over-http"
    restart: unless-stopped

  seq:
    image: datalust/seq
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"  # Expose MongoDB port for Compass